<!DOCTYPE html>


  <html class="light page-post">


<head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="utf-8">
  
  <title>9. JavaSE-Java异常处理 | SomnambulistOfChina</title>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  
    <meta name="keywords" content="Java SE,">
  

  <meta name="description" content="#9.1 异常的概述 9.1.1 什么是异常  异常，又称为例外，是指不可预知的非正常的情况，例如：正常开车突然路口窜出一条狗来，或者正常上下班的路上，某个街角偶遇了爱情，或者在每天晨跑的小树林遭遇了歹徒。这些突发的情况的发生是不可预知的，where,when……，但是如果处理好了，美好的生活不受影响，可以继续，如果处理不好，可能就“挂”了。 Java语言将程序执行中发生的不正常情况称为“异常”，">
<meta name="keywords" content="Java SE">
<meta property="og:type" content="article">
<meta property="og:title" content="9. JavaSE-Java异常处理">
<meta property="og:url" content="http://yoursite.com/2016/12/24/9. JavaSE-Java异常处理/index.html">
<meta property="og:site_name" content="SomnambulistOfChina">
<meta property="og:description" content="#9.1 异常的概述 9.1.1 什么是异常  异常，又称为例外，是指不可预知的非正常的情况，例如：正常开车突然路口窜出一条狗来，或者正常上下班的路上，某个街角偶遇了爱情，或者在每天晨跑的小树林遭遇了歹徒。这些突发的情况的发生是不可预知的，where,when……，但是如果处理好了，美好的生活不受影响，可以继续，如果处理不好，可能就“挂”了。 Java语言将程序执行中发生的不正常情况称为“异常”，">
<meta property="og:locale" content="Java EE">
<meta property="og:image" content="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530165032.png">
<meta property="og:image" content="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530165238.png">
<meta property="og:image" content="http://note.youdao.com/yws/res/6111/E0EEA67E326B44F88C522355472DF277">
<meta property="og:image" content="http://note.youdao.com/yws/res/6115/6B2236572F2549EEA6C1290778B0667D">
<meta property="og:image" content="http://note.youdao.com/yws/res/6118/2A148296222146499CEC8890FAE7A502">
<meta property="og:image" content="http://note.youdao.com/yws/res/6120/E6C67A0CEABC4234A6F158AB8563DAAD">
<meta property="og:image" content="http://note.youdao.com/yws/res/6122/047861140C034F1AA897892453C30046">
<meta property="og:image" content="http://note.youdao.com/yws/res/6124/6B44AF6FC34148B9A9EE29CB92F31693">
<meta property="og:image" content="http://note.youdao.com/yws/res/6131/C962A64258584FDEB8E0ADEF0B71771E">
<meta property="og:image" content="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530171700.png">
<meta property="og:image" content="http://note.youdao.com/yws/res/6167/B96E6C21D3064CFE8883B3FD2DD151A2">
<meta property="og:updated_time" content="2019-06-04T01:25:38.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="9. JavaSE-Java异常处理">
<meta name="twitter:description" content="#9.1 异常的概述 9.1.1 什么是异常  异常，又称为例外，是指不可预知的非正常的情况，例如：正常开车突然路口窜出一条狗来，或者正常上下班的路上，某个街角偶遇了爱情，或者在每天晨跑的小树林遭遇了歹徒。这些突发的情况的发生是不可预知的，where,when……，但是如果处理好了，美好的生活不受影响，可以继续，如果处理不好，可能就“挂”了。 Java语言将程序执行中发生的不正常情况称为“异常”，">
<meta name="twitter:image" content="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530165032.png">

  

  
    <link rel="icon" href="/favicon.ico">
  

  <link href="/css/styles.css?v=c114cbeddx" rel="stylesheet">


  
    <link rel="stylesheet" href="/css/personal-style.css">
  

  
<!-- Google Analytics -->
<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-38189205-1', 'auto');
ga('send', 'pageview');

</script>
<!-- End Google Analytics -->


  
  <script type="text/javascript">
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "//hm.baidu.com/hm.js?99d997f72fffd95d0fd1477dd657eafc";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>


  
  <script type="text/javascript">
	(function(){
	    var bp = document.createElement('script');
	    var curProtocol = window.location.protocol.split(':')[0];
	    if (curProtocol === 'https') {
	        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';        
	    }
	    else {
	        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
	    }
	    var s = document.getElementsByTagName("script")[0];
	    s.parentNode.insertBefore(bp, s);
	})();
  </script>



  
    <script async src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
    <link rel="stylesheet" href="//cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css">
  
  
</head>
</html>
<body>


  
    <span id="toolbox-mobile" class="toolbox-mobile">更多</span>
  

  <div class="post-header CENTER">
   
  <div class="toolbox">
    <a class="toolbox-entry" href="/">
      <span class="toolbox-entry-text">更多</span>
      <i class="icon-angle-down"></i>
      <i class="icon-home"></i>
    </a>
    <ul class="list-toolbox">
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/archives/" rel="noopener noreferrer" target="_self">
            博客
          </a>
        </li>
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/category/" rel="noopener noreferrer" target="_self">
            分类
          </a>
        </li>
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/tag/" rel="noopener noreferrer" target="_self">
            标签
          </a>
        </li>
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/link/" rel="noopener noreferrer" target="_self">
            友链
          </a>
        </li>
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/about/" rel="noopener noreferrer" target="_self">
            关于
          </a>
        </li>
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/search/" rel="noopener noreferrer" target="_self">
            搜索
          </a>
        </li>
      
        <li class="item-toolbox">
          <a class="CIRCLE" href="/atom.xml" rel="noopener noreferrer" target="_blank">
            RSS
          </a>
        </li>
      
    </ul>
  </div>


</div>


  <div id="toc" class="toc-article">
    <strong class="toc-title">文章目录</strong>
    <ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#9-1-1-什么是异常"><span class="toc-text">9.1.1 什么是异常</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-1-2-Java异常的堆栈式抛出机制"><span class="toc-text">9.1.2 Java异常的堆栈式抛出机制</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#1-ArrayIndexOutOfBoundsException数组下标越界异常"><span class="toc-text">1. ArrayIndexOutOfBoundsException数组下标越界异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#2-NumberFormatException数字格式化异常"><span class="toc-text">2. NumberFormatException数字格式化异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#3-ArithmeticException算术异常"><span class="toc-text">3. ArithmeticException算术异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#4-结论"><span class="toc-text">4. 结论</span></a></li></ol></li></ol><li class="toc-item toc-level-1"><a class="toc-link" href="#9-2-异常体系结构"><span class="toc-text">9.2 异常体系结构</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#9-2-1-异常的分类"><span class="toc-text">9.2.1 异常的分类</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-2-2-Throwable"><span class="toc-text">9.2.2 Throwable</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-2-3-Error"><span class="toc-text">9.2.3 Error</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-2-4-Exception"><span class="toc-text">9.2.4 Exception</span></a></li></ol></li><li class="toc-item toc-level-1"><a class="toc-link" href="#9-3-异常处理机制"><span class="toc-text">9.3 异常处理机制</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#9-3-1-捕获异常（try…catch…finally）"><span class="toc-text">9.3.1 捕获异常（try…catch…finally）</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#1-try"><span class="toc-text">1. try</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#2-catch"><span class="toc-text">2. catch</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#3-finally"><span class="toc-text">3. finally</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#4-运行示意图"><span class="toc-text">4. 运行示意图</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#5-示例"><span class="toc-text">5. 示例</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#9-3-2-显式声明抛出异常（throws）"><span class="toc-text">9.3.2 显式声明抛出异常（throws）</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#1-示例代码"><span class="toc-text">1. 示例代码</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#2-重写方法对throws异常的要求"><span class="toc-text">2. 重写方法对throws异常的要求</span></a></li></ol></li></ol></li></ol></li><li class="toc-item toc-level-1"><a class="toc-link" href="#9-4-手动抛出异常（throw）"><span class="toc-text">9.4 手动抛出异常（throw）</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#9-5-自定义异常"><span class="toc-text">9.5 自定义异常</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#9-6-finally与return"><span class="toc-text">9.6 finally与return</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#9-6-1-从finally的return回来"><span class="toc-text">9.6.1 从finally的return回来</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-6-2-从catch的return回来"><span class="toc-text">9.6.2 从catch的return回来</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-6-3-从try的return回来"><span class="toc-text">9.6.3 从try的return回来</span></a></li></ol></li><li class="toc-item toc-level-1"><a class="toc-link" href="#9-7-小结"><span class="toc-text">9.7 小结</span></a>
  </li></div>



<div class="content content-post CENTER">
   <article id="post-9. JavaSE-Java异常处理" class="article article-type-post" itemprop="blogPost">
  <header class="article-header">
    <h1 class="post-title">9. JavaSE-Java异常处理</h1>

    <div class="article-meta">
      <span>
        <i class="icon-calendar"></i>
        <span>2016.12.24</span>
      </span>

      
        <span class="article-author">
          <i class="icon-user"></i>
          <span>SomnambulistOfChina</span>
        </span>
      

      
  <span class="article-category">
    <i class="icon-list"></i>
    <a class="article-category-link" href="/categories/JavaSE基础笔记/">JavaSE基础笔记</a>
  </span>



      

      
      <i class="fa fa-eye"></i> 
        <span id="busuanzi_container_page_pv">
           &nbsp热度 <span id="busuanzi_value_page_pv">
           <i class="fa fa-spinner fa-spin"></i></span>℃
        </span>
      
      
    </div>
  </header>

  <div class="article-content">
    
      <p>#9.1 异常的概述</p>
<h2 id="9-1-1-什么是异常"><a href="#9-1-1-什么是异常" class="headerlink" title="9.1.1 什么是异常"></a>9.1.1 什么是异常</h2><blockquote>
<ul>
<li>异常，又称为例外，是指不可预知的非正常的情况，例如：正常开车突然路口窜出一条狗来，或者正常上下班的路上，某个街角偶遇了爱情，或者在每天晨跑的小树林遭遇了歹徒。这些突发的情况的发生是不可预知的，where,when……，但是如果处理好了，美好的生活不受影响，可以继续，如果处理不好，可能就“挂”了。</li>
<li>Java语言将程序执行中发生的不正常情况称为“异常”，异常是一种对程序运行过程中发生错误时进行通知的机制。如：网络连接失败、用户输入错误或打开文件失败等。</li>
</ul>
</blockquote>
<p> <img src="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530165032.png" alt></p>
<h2 id="9-1-2-Java异常的堆栈式抛出机制"><a href="#9-1-2-Java异常的堆栈式抛出机制" class="headerlink" title="9.1.2 Java异常的堆栈式抛出机制"></a>9.1.2 Java异常的堆栈式抛出机制</h2><p>示例代码：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line">public class TestException &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		int a = Integer.parseInt(args[0]);</span><br><span class="line">		int b = Integer.parseInt(args[1]);</span><br><span class="line">		System.out.println(a + &quot;/&quot; + b + &quot;=&quot; + a/b);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>命令行执行：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">java  com.exception.TestException  12  3</span><br></pre></td></tr></table></figure>
<p>运行结果显示12/3=4，结果正常。</p>
<h3 id="1-ArrayIndexOutOfBoundsException数组下标越界异常"><a href="#1-ArrayIndexOutOfBoundsException数组下标越界异常" class="headerlink" title="1. ArrayIndexOutOfBoundsException数组下标越界异常"></a>1. ArrayIndexOutOfBoundsException数组下标越界异常</h3><p>命令行执行：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">java  com.exception.TestException</span><br></pre></td></tr></table></figure>
<p>出现异常形式，如图9-1：</p>
<p><img src="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530165238.png" alt></p>
<h3 id="2-NumberFormatException数字格式化异常"><a href="#2-NumberFormatException数字格式化异常" class="headerlink" title="2. NumberFormatException数字格式化异常"></a>2. NumberFormatException数字格式化异常</h3><p>命令行执行：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">java  com.exception.TestException  a  b</span><br></pre></td></tr></table></figure>
<p>出现异常形式，如图9-2：</p>
<p><img src="http://note.youdao.com/yws/res/6111/E0EEA67E326B44F88C522355472DF277" alt="image"></p>
<h3 id="3-ArithmeticException算术异常"><a href="#3-ArithmeticException算术异常" class="headerlink" title="3. ArithmeticException算术异常"></a>3. ArithmeticException算术异常</h3><p>命令行执行：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">java  com.exception.TestException  12  0</span><br></pre></td></tr></table></figure>
<p>出现异常形式，如图9-3：</p>
<p><img src="http://note.youdao.com/yws/res/6115/6B2236572F2549EEA6C1290778B0667D" alt="image"></p>
<h3 id="4-结论"><a href="#4-结论" class="headerlink" title="4. 结论"></a>4. 结论</h3><p>在Java中异常以对象的形式出现，不同的异常对象中封装了相应的错误信息。<br>Java是采用面向对象的方式来处理异常的。处理过程：</p>
<ul>
<li>抛出异常：在执行一个方法时，如果在某句代码发生异常，则会在该句代码处生成代表该异常的一个对象，停止当前执行路径，并把异常对象提交给JRE，不同的异常对象中封装了相应的错误信息。</li>
<li>捕获异常：JRE得到该异常后，寻找相应的代码来处理该异常。JRE在方法的调用栈中查找，从生成异常的方法开始回溯，直到找到相应的异常处理代码为止。如果没有找到处理代码，那么程序终止运行<br>Java中异常的是以堆栈式抛出机制来进行错误通知的，如图10-4。</li>
</ul>
<p><img src="http://note.youdao.com/yws/res/6118/2A148296222146499CEC8890FAE7A502" alt="image"></p>
<h1 id="9-2-异常体系结构"><a href="#9-2-异常体系结构" class="headerlink" title="9.2 异常体系结构"></a>9.2 异常体系结构</h1><p>如10.1.2所示的ArrayIndexOutOfBoundsException数组下标越界异常，NumberFormatException数字格式化异常，ArithmeticException算术异常，查看它们的API，例如图9-5,9-6,9-7。</p>
<p><img src="http://note.youdao.com/yws/res/6120/E6C67A0CEABC4234A6F158AB8563DAAD" alt="image"></p>
<p><img src="http://note.youdao.com/yws/res/6122/047861140C034F1AA897892453C30046" alt="image"></p>
<p><img src="http://note.youdao.com/yws/res/6124/6B44AF6FC34148B9A9EE29CB92F31693" alt="image"></p>
<h2 id="9-2-1-异常的分类"><a href="#9-2-1-异常的分类" class="headerlink" title="9.2.1 异常的分类"></a>9.2.1 异常的分类</h2><p>Java语言提供了两大类异常，如图9-8：</p>
<ul>
<li>编译时异常（受检异常Checked）<br>编译时异常：指程序中必须接受检查和处理的异常，由Exception 类表示。</li>
<li>运行时异常（非受检异常UnChecked）<br>运行时异常：程序中可以不接受检查和处理，或致命性错误异常，由RuntimeException类或Error类表示。</li>
</ul>
<p><img src="http://note.youdao.com/yws/res/6131/C962A64258584FDEB8E0ADEF0B71771E" alt="image"></p>
<h2 id="9-2-2-Throwable"><a href="#9-2-2-Throwable" class="headerlink" title="9.2.2 Throwable"></a>9.2.2 Throwable</h2><ul>
<li>Throwable 类是 Java 语言中所有错误或异常的超类。只有当对象是此类（或其子类之一）的实例时，才能通过 Java 虚拟机或者 Java throw 语句抛出。类似地，只有此类或其子类之一才可以是 catch 子句中的参数类型。 </li>
<li>两个子类的实例，Error 和 Exception，通常用于指示发生了异常情况。通常，这些实例是在异常情况的上下文中新近创建的，因此包含了相关的信息（比如堆栈跟踪数据）。 <h2 id="9-2-3-Error"><a href="#9-2-3-Error" class="headerlink" title="9.2.3 Error"></a>9.2.3 Error</h2></li>
<li>Error 是 Throwable 的子类，用于指示合理的应用程序不应该试图捕获的严重问题。大多数这样的错误都是异常条件。虽然 ThreadDeath 错误是一个“正规”的条件，但它也是 Error 的子类，因为大多数应用程序都不应该试图捕获它。 </li>
<li>在执行该方法期间，无需在其 throws 子句中声明可能抛出但是未能捕获的 Error 的任何子类，因为这些错误可能是再也不会发生的异常条件。 <h2 id="9-2-4-Exception"><a href="#9-2-4-Exception" class="headerlink" title="9.2.4 Exception"></a>9.2.4 Exception</h2>Exception 类及其子类是 Throwable 的一种形式，它指出了合理的应用程序想要捕获的条件。<br>应该在程序中尽可能的预知并处理异常。</li>
<li>checkedException：受检异常。这一类异常，编译时必须对其进行处理，如果不处理，编译不通过。（checked表示编译器检查过已经处理过的）。例如：疲劳必须休息、喝酒必须不能开车、刹车必须好用。</li>
<li>RuntimeException（uncheckedException）：运行时异常（非受检异常）。一类特殊的异常，如被0除、数组下标越界等，其产生比较频繁，处理麻烦，如果显式的声明或捕获将会对程序可读性和运行效率影响很大。因此由系统自动检测并将它们交给缺省的异常处理程序，即交给JVM处理，用户不显式处理。但是应该尽量避免！！！<br>例如：前车急刹车、有人加塞、路口突然窜出的电动车等等。换句话说，出现RuntimeException一定是你的问题，可以不捕获，因为小心点这些异常是可以避免的，例如：数组下标越界异常ArrayIndexOutOfBoundsException，空指针异常NullPointerException，类型转换异常ClassCastException等等。<h1 id="9-3-异常处理机制"><a href="#9-3-异常处理机制" class="headerlink" title="9.3 异常处理机制"></a>9.3 异常处理机制</h1><h2 id="9-3-1-捕获异常（try…catch…finally）"><a href="#9-3-1-捕获异常（try…catch…finally）" class="headerlink" title="9.3.1 捕获异常（try…catch…finally）"></a>9.3.1 捕获异常（try…catch…finally）</h2>可使用try…catch…finally语句捕获异常，避免程序不正常终止  </li>
</ul>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">语法：</span><br><span class="line">try &#123;</span><br><span class="line">		……</span><br><span class="line">	&#125; [catch (&lt;异常类型&gt;  &lt;异常引用变量&gt;) &#123;</span><br><span class="line">		……</span><br><span class="line">	&#125; ]*  </span><br><span class="line">[finally &#123;</span><br><span class="line">		……</span><br><span class="line">	&#125;]</span><br></pre></td></tr></table></figure>
<p>说明：<br>（1）*可使用多个catch子句捕获多个异常，[]表示可选。<br>（2）可以有如下组合形式：<code>try...catch，try...finally，try...catch...finally</code>。  </p>
<h3 id="1-try"><a href="#1-try" class="headerlink" title="1. try"></a>1. try</h3><ul>
<li>try块中是可能发生异常的代码。其中某句代码发生异常，就会跳过try块中该句后面的代码，该句代码处会产生并抛出一种或几种类型的异常对象，它后面的catch语句要分别对这些异常做相应的处理。  </li>
<li>注意：<br>一个try必须带一个catch块或finally块或两者都有，即try块不能单独存在。<br>当异常处理的代码执行结束以后，是不会回到try语句块去执行尚未执行的代码的。只会执行try…catch…finally后面的代码。  <h3 id="2-catch"><a href="#2-catch" class="headerlink" title="2. catch"></a>2. catch</h3></li>
<li>每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。  </li>
<li>catch块如果多个，异常对象将从上到下依次匹配类型，一旦某个catch的异常类型匹配成功，其他的catch将不再执行，即一个异常只能进入一个catch块。  </li>
<li>catch可以有多个，但是多个catch中的异常类型如果是“互斥关系（没有继承关系）”，顺序随意；如果是“包含关系（继承关系）”，必须小上大下/子上父下。<h3 id="3-finally"><a href="#3-finally" class="headerlink" title="3. finally"></a>3. finally</h3></li>
<li>有些语句，不管是否发生了异常，都必须要执行，那么就可以把这样的语句放到finally语句块中。</li>
<li>通常在finally中关闭程序块已打开的资源，比如：文件流、释放数据库连接等。<h3 id="4-运行示意图"><a href="#4-运行示意图" class="headerlink" title="4. 运行示意图"></a>4. 运行示意图</h3>try…catch…finally的运行示意图，如图10-9</li>
</ul>
<p><img src="https://raw.githubusercontent.com/SomnambulistOfChina/photo_GitHub/master/photo/20190530171700.png" alt></p>
<h3 id="5-示例"><a href="#5-示例" class="headerlink" title="5. 示例"></a>5. 示例</h3><p>####（1）示例1</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">public class TestException &#123;</span><br><span class="line"></span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		try &#123;</span><br><span class="line">			int a = Integer.parseInt(args[0]);</span><br><span class="line">			int b = Integer.parseInt(args[1]);</span><br><span class="line">			System.out.println(a + &quot;/&quot; + b + &quot;=&quot; + a/b);</span><br><span class="line">		&#125; catch (NumberFormatException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125; catch (ArrayIndexOutOfBoundsException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125; catch (ArithmeticException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;</span><br><span class="line">		System.out.println(&quot;程序继续...&quot;);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>####（2）示例2</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">import java.io.FileNotFoundException;</span><br><span class="line">import java.io.FileReader;</span><br><span class="line">import java.io.IOException;</span><br><span class="line"></span><br><span class="line">public class TestFileReader &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		FileReader fr = null;</span><br><span class="line">		try &#123;</span><br><span class="line">			fr = new FileReader(&quot;d:/a.txt&quot;);</span><br><span class="line">			char c = (char) fr.read();</span><br><span class="line">			System.out.println(c);</span><br><span class="line">		&#125; catch (FileNotFoundException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125; catch (IOException e) &#123;</span><br><span class="line">			//IOException不能放前面，因为FileNotFoundException 是子类</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125; finally&#123;</span><br><span class="line">              //可以嵌套</span><br><span class="line">			try &#123;</span><br><span class="line">				if(fr!=null)&#123;//需要判断非空</span><br><span class="line">					fr.close();</span><br><span class="line">				&#125;</span><br><span class="line">			&#125; catch (IOException e) &#123;</span><br><span class="line">				e.printStackTrace();</span><br><span class="line">			&#125;</span><br><span class="line">        &#125;</span><br><span class="line">        System.out.println(&quot;程序继续...&quot;);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="9-3-2-显式声明抛出异常（throws）"><a href="#9-3-2-显式声明抛出异常（throws）" class="headerlink" title="9.3.2 显式声明抛出异常（throws）"></a>9.3.2 显式声明抛出异常（throws）</h3><ul>
<li>如果一个方法出现Checked Exception，但是并不能确定如何处理这种异常或者不立刻处理它，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。</li>
<li>在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。如果一个方法抛出多个受检异常，就必须在方法的签名中列出所有的异常，之间以逗号隔开。<h4 id="1-示例代码"><a href="#1-示例代码" class="headerlink" title="1. 示例代码"></a>1. 示例代码</h4></li>
</ul>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">import java.io.FileNotFoundException;</span><br><span class="line">import java.io.FileReader;</span><br><span class="line">import java.io.IOException;</span><br><span class="line"></span><br><span class="line">public class TestFileReader2 &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		try &#123;</span><br><span class="line">			readFile(&quot;d:/a.txt&quot;);</span><br><span class="line">		&#125; catch (IOException e) &#123;</span><br><span class="line">			e.printStackTrace();</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">	</span><br><span class="line">	public static void readFile(String filename) throws FileNotFoundException,IOException&#123;</span><br><span class="line">		FileReader fr = new FileReader(&quot;d:/a.txt&quot;);</span><br><span class="line">		char c = (char) fr.read();</span><br><span class="line">		System.out.println(c);</span><br><span class="line">		fr.close();</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h4 id="2-重写方法对throws异常的要求"><a href="#2-重写方法对throws异常的要求" class="headerlink" title="2. 重写方法对throws异常的要求"></a>2. 重写方法对throws异常的要求</h4><p>重写方法不能抛出比被重写方法范围更大的异常类型。在多态的情况下，对重写方法的调用–异常的捕获按父类声明的异常处理。即</p>
<ul>
<li>父类被重写的方法没有声明抛出checked受检异常，那么重写的方法也不能声明抛出异常</li>
<li>子类重写方法声明抛出的异常的类型和父类被重写的方法声明抛出异常类型一致</li>
<li>子类重写方法声明抛出的异常的类型是父类被重写的方法声明抛出异常的子类</li>
<li>子类重写方法可以在方法内部处理异常，而不声明抛出异常<br>正确的示例代码：</li>
</ul>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">class A&#123;</span><br><span class="line">	public void method()throws IOException&#123;&#125;</span><br><span class="line">&#125;</span><br><span class="line">class B extends A&#123;</span><br><span class="line">	public void method()&#123;&#125;</span><br><span class="line">&#125;</span><br><span class="line">class C extends A&#123;</span><br><span class="line">	public void method() throws FileNotFoundException&#123;&#125;</span><br><span class="line">&#125;</span><br><span class="line">class D extends A&#123;</span><br><span class="line">	public void method() throws IOException,FileNotFoundException&#123;&#125;</span><br><span class="line">&#125;</span><br><span class="line">class E extends A&#123;</span><br><span class="line">	public void method() throws IOException,RuntimeException&#123;&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>错误的示例代码：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">class A&#123;</span><br><span class="line">	public void method()throws IOException&#123;&#125;</span><br><span class="line">&#125;</span><br><span class="line">class F extends A&#123;</span><br><span class="line">	public void method() throws Exception &#123;&#125;</span><br><span class="line">&#125;</span><br><span class="line">class G extends A&#123;</span><br><span class="line">	public void method() throws IOException,SQLException&#123;&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="9-4-手动抛出异常（throw）"><a href="#9-4-手动抛出异常（throw）" class="headerlink" title="9.4 手动抛出异常（throw）"></a>9.4 手动抛出异常（throw）</h1><p>Java异常类对象除在程序执行过程中出现异常时由系统自动生成并抛出，也可以根据需要手动创建并抛出。可以抛出的异常必须是Throwable或其子类的实例。<br>首先要创建异常类对象，然后通过throw语句实现抛出操作，提交给Java运行环境。<br>语法格式：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">throw 异常对象;</span><br></pre></td></tr></table></figure>
<p>不管系统自动生成的还是手动创建的，异常对象一旦抛出都需要使用捕获try…catch或继续抛出throws的方式处理。<br>其次，throw语句可以代替return语句结束方法。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">public class TestThrow &#123;</span><br><span class="line">	public static void check(String username,String password)&#123;</span><br><span class="line">		if(username==null || &quot;&quot;.equals(username.trim()))&#123;</span><br><span class="line">			throw new RuntimeException(&quot;用户名不能为空&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">		if(password==null || &quot;&quot;.equals(password.trim()))&#123;</span><br><span class="line">			throw new RuntimeException(&quot;密码不能为空&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="9-5-自定义异常"><a href="#9-5-自定义异常" class="headerlink" title="9.5 自定义异常"></a>9.5 自定义异常</h1><ul>
<li>在程序中，可能会遇到任何标准异常类都没能充分的描述清楚的问题，这种情况下可以创建自己的异常类。</li>
<li>从Exception类或者它的子类派生一个子类即可</li>
<li>习惯上，自定义异常类应该包含2个构造器：一个是无参构造，另一个是带有详细信息的构造器</li>
<li>自定义的异常只能通过throw抛出。</li>
<li>自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。</li>
</ul>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">public class TestMyException &#123;</span><br><span class="line">	public static void login(String username,String password) throws WrongUsernameOrPassWordException&#123;</span><br><span class="line">		if(!(&quot;admin&quot;.equals(username) &amp;&amp; &quot;123&quot;.equals(password)))&#123;</span><br><span class="line">			throw new WrongUsernameOrPassWordException(&quot;用户名或密码错误&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">		System.out.println(&quot;登录成功&quot;);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br><span class="line">class WrongUsernameOrPassWordException extends Exception&#123;</span><br><span class="line">	private static final long serialVersionUID = 1L;</span><br><span class="line"></span><br><span class="line">	public WrongUsernameOrPassWordException() &#123;</span><br><span class="line">		super();</span><br><span class="line">	&#125;</span><br><span class="line"></span><br><span class="line">	public WrongUsernameOrPassWordException(String message) &#123;</span><br><span class="line">		super(message);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="9-6-finally与return"><a href="#9-6-finally与return" class="headerlink" title="9.6 finally与return"></a>9.6 finally与return</h1><p>执行顺序：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">1、执行try,catch，给“返回值”临时变量赋值</span><br><span class="line">2、执行finally</span><br><span class="line">3、return</span><br><span class="line">return语句两个作用：给返回值赋值，结束方法运行</span><br></pre></td></tr></table></figure>
<h2 id="9-6-1-从finally的return回来"><a href="#9-6-1-从finally的return回来" class="headerlink" title="9.6.1 从finally的return回来"></a>9.6.1 从finally的return回来</h2><p>示例代码：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">public class TestReturn &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		int result = test(&quot;a&quot;);</span><br><span class="line">		System.out.println(result);</span><br><span class="line">	&#125;</span><br><span class="line"></span><br><span class="line">	public static int test(String str)&#123;</span><br><span class="line">		try&#123;</span><br><span class="line">			Integer.parseInt(str);</span><br><span class="line">			return 1;</span><br><span class="line">		&#125;catch(NumberFormatException e)&#123;</span><br><span class="line">			return -1;</span><br><span class="line">		&#125;finally&#123;</span><br><span class="line">            System.out.println(&quot;test结束&quot;);</span><br><span class="line">			return 0;</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行结果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">test结束</span><br><span class="line">0</span><br></pre></td></tr></table></figure>
<h2 id="9-6-2-从catch的return回来"><a href="#9-6-2-从catch的return回来" class="headerlink" title="9.6.2 从catch的return回来"></a>9.6.2 从catch的return回来</h2><p>示例代码</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">public class TestReturn &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		int result = test(&quot;a&quot;);</span><br><span class="line">		System.out.println(result);</span><br><span class="line">	&#125;</span><br><span class="line"></span><br><span class="line">	public static int test(String str)&#123;</span><br><span class="line">		try&#123;</span><br><span class="line">			Integer.parseInt(str);</span><br><span class="line">			return 1;</span><br><span class="line">		&#125;catch(NumberFormatException e)&#123;</span><br><span class="line">			return -1;</span><br><span class="line">		&#125;finally&#123;</span><br><span class="line">			System.out.println(&quot;test结束&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行结果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">test结束</span><br><span class="line">-1</span><br></pre></td></tr></table></figure>
<h2 id="9-6-3-从try的return回来"><a href="#9-6-3-从try的return回来" class="headerlink" title="9.6.3 从try的return回来"></a>9.6.3 从try的return回来</h2><p>示例代码：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">package com.exception;</span><br><span class="line"></span><br><span class="line">public class TestReturn &#123;</span><br><span class="line">	public static void main(String[] args) &#123;</span><br><span class="line">		int result = test(&quot;12&quot;);</span><br><span class="line">		System.out.println(result);</span><br><span class="line">	&#125;</span><br><span class="line"></span><br><span class="line">	public static int test(String str)&#123;</span><br><span class="line">		try&#123;</span><br><span class="line">			Integer.parseInt(str);</span><br><span class="line">			return 1;</span><br><span class="line">		&#125;catch(NumberFormatException e)&#123;</span><br><span class="line">			return -1;</span><br><span class="line">		&#125;finally&#123;</span><br><span class="line">			System.out.println(&quot;test结束&quot;);</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行结果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">test结束</span><br><span class="line">1</span><br></pre></td></tr></table></figure>
<h1 id="9-7-小结"><a href="#9-7-小结" class="headerlink" title="9.7 小结"></a>9.7 小结</h1><ul>
<li>要避免使用异常处理代替错误处理，这样会降低程序的清晰性，并且效率低下。</li>
<li>不要进行小粒度的异常处理——应该将整个任务包装在一个try语句块中。</li>
<li>异常往往在高层处理。例如：（高层）领导—&gt;员工。调用关系。有问题赶紧上报<br>Java的异常处理机制总体示意图，如图10-10：</li>
</ul>
<p><img src="http://note.youdao.com/yws/res/6167/B96E6C21D3064CFE8883B3FD2DD151A2" alt="image"></p>

    
  </div>

</article>


   
  <div class="text-center donation">
    <div class="inner-donation">
      <span class="btn-donation">支持一下</span>
      <div class="donation-body">
        <div class="tip text-center">扫一扫，支持forsigner</div>
        <ul>
        
          <li class="item">
            
              <span>微信扫一扫</span>
            
            <img src="/images/qr-wechat.jpeg" alt>
          </li>
        
          <li class="item">
            
              <span>支付宝扫一扫</span>
            
            <img src="/images/qr-alipay.jpeg" alt>
          </li>
        
        </ul>
      </div>
    </div>
  </div>


   
  <div class="box-prev-next clearfix">
    <a class="show pull-left" href="/2016/11/12/8. JavaSE-枚举与注解/">
        <i class="icon icon-angle-left"></i>
    </a>
    <a class="show pull-right" href="/2017/01/01/10. JavaSE-常用类/">
        <i class="icon icon-angle-right"></i>
    </a>
  </div>




</div>


  <a id="backTop" class="back-top">
    <i class="icon-angle-up"></i>
  </a>




  <div class="modal" id="modal">
  <span id="cover" class="cover hide"></span>
  <div id="modal-dialog" class="modal-dialog hide-dialog">
    <div class="modal-header">
      <span id="close" class="btn-close">关闭</span>
    </div>
    <hr>
    <div class="modal-body">
      <ul class="list-toolbox">
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/archives/" rel="noopener noreferrer" target="_self">
              博客
            </a>
          </li>
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/category/" rel="noopener noreferrer" target="_self">
              分类
            </a>
          </li>
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/tag/" rel="noopener noreferrer" target="_self">
              标签
            </a>
          </li>
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/link/" rel="noopener noreferrer" target="_self">
              友链
            </a>
          </li>
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/about/" rel="noopener noreferrer" target="_self">
              关于
            </a>
          </li>
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/search/" rel="noopener noreferrer" target="_self">
              搜索
            </a>
          </li>
        
          <li class="item-toolbox">
            <a class="CIRCLE" href="/atom.xml" rel="noopener noreferrer" target="_blank">
              RSS
            </a>
          </li>
        
      </ul>

    </div>
  </div>
</div>



  
      <div class="fexo-comments comments-post">
    

    

    
    

    

    
    

    <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/valine@latest/dist/Valine.min.js"></script>
    <div id="comment" class="vcomment"></div>
    <script>
        var notify = 'false' == true ? true : false;
        var verify = 'false' == true ? true : false;
        var GUEST_INFO = ['nick','mail','link'];
        var guest_info = 'nick,mail,link'.split(',').filter(function(item){
            return GUEST_INFO.indexOf(item) > -1
        });
        guest_info = guest_info.length == 0 ? GUEST_INFO :guest_info;
        window.valine = new Valine({
            el: '.vcomment',
            notify: notify,
            verify: verify,
            appId: "b8cfVAxSX9whYsIOMmxwCicp-gzGzoHsz",
            appKey: "klYDKAeEh6GPa0wnf22lQd96",
            avatar:'identicon',
            placeholder: "ヾﾉ≧∀≦)o 来呀！快活呀！~",
            guest_info:guest_info,
            pageSize:'10'
        });
    </script>
  
    

  </div>

  

  <script type="text/javascript">
  function loadScript(url, callback) {
    var script = document.createElement('script')
    script.type = 'text/javascript';

    if (script.readyState) { //IE
      script.onreadystatechange = function() {
        if (script.readyState == 'loaded' ||
          script.readyState == 'complete') {
          script.onreadystatechange = null;
          callback();
        }
      };
    } else { //Others
      script.onload = function() {
        callback();
      };
    }

    script.src = url;
    document.getElementsByTagName('head')[0].appendChild(script);
  }

  window.onload = function() {
    loadScript('/js/bundle.js?235683', function() {
      // load success
    });
  }
</script>

</body>
</html>
